[project]
name = "nai-07"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium[box2d, other]>=0.30.1",
    "numpy>=2.4.1",
]
